# Welcome to Jekyll!
#

# Site settings
title: Shravan Murali
description: Portfolio of Shravan Murali
owner: Shravan Murali
first_published: 2016 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shravan97.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/shrvn97
  github: https://github.com/shravan97
  linkedin-square: https://linkedin.com/in/shravan97
  facebook-official: https://facebook.com/shravan97
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
